#include <common.h>
extern char _u_boot_list_2_bootdev_hunter_2_eth_bootdev_hunt[];
__ADDRESSABLE(_u_boot_list_2_bootdev_hunter_2_eth_bootdev_hunt);
extern char _u_boot_list_2_bootdev_hunter_2_mmc_bootdev_hunter[];
__ADDRESSABLE(_u_boot_list_2_bootdev_hunter_2_mmc_bootdev_hunter);
extern char _u_boot_list_2_bootdev_hunter_2_usb_bootdev_hunter[];
__ADDRESSABLE(_u_boot_list_2_bootdev_hunter_2_usb_bootdev_hunter);
extern char _u_boot_list_2_cmd_2_ab_select[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ab_select);
extern char _u_boot_list_2_cmd_2_abootimg[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_abootimg);
extern char _u_boot_list_2_cmd_2_adtimg[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_adtimg);
extern char _u_boot_list_2_cmd_2_askenv[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_askenv);
extern char _u_boot_list_2_cmd_2_avb[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_avb);
extern char _u_boot_list_2_cmd_2_base[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_base);
extern char _u_boot_list_2_cmd_2_bcb[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bcb);
extern char _u_boot_list_2_cmd_2_bdinfo[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bdinfo);
extern char _u_boot_list_2_cmd_2_bind[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bind);
extern char _u_boot_list_2_cmd_2_blkcache[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_blkcache);
extern char _u_boot_list_2_cmd_2_boot[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_boot);
extern char _u_boot_list_2_cmd_2_boota[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_boota);
extern char _u_boot_list_2_cmd_2_bootd[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bootd);
extern char _u_boot_list_2_cmd_2_bootefi[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bootefi);
extern char _u_boot_list_2_cmd_2_bootelf[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bootelf);
extern char _u_boot_list_2_cmd_2_bootflow[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bootflow);
extern char _u_boot_list_2_cmd_2_booti[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_booti);
extern char _u_boot_list_2_cmd_2_bootm[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bootm);
extern char _u_boot_list_2_cmd_2_bootp[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bootp);
extern char _u_boot_list_2_cmd_2_bootvx[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_bootvx);
extern char _u_boot_list_2_cmd_2_btrsubvol[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_btrsubvol);
extern char _u_boot_list_2_cmd_2_clk[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_clk);
extern char _u_boot_list_2_cmd_2_cmp[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_cmp);
extern char _u_boot_list_2_cmd_2_coninfo[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_coninfo);
extern char _u_boot_list_2_cmd_2_cp[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_cp);
extern char _u_boot_list_2_cmd_2_cyclic[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_cyclic);
extern char _u_boot_list_2_cmd_2_dcache[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_dcache);
extern char _u_boot_list_2_cmd_2_dhcp[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_dhcp);
extern char _u_boot_list_2_cmd_2_dm[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_dm);
extern char _u_boot_list_2_cmd_2_echo[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_echo);
extern char _u_boot_list_2_cmd_2_editenv[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_editenv);
extern char _u_boot_list_2_cmd_2_eeprom[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_eeprom);
extern char _u_boot_list_2_cmd_2_eficonfig[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_eficonfig);
extern char _u_boot_list_2_cmd_2_env[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_env);
extern char _u_boot_list_2_cmd_2_exit[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_exit);
extern char _u_boot_list_2_cmd_2_ext2load[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ext2load);
extern char _u_boot_list_2_cmd_2_ext2ls[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ext2ls);
extern char _u_boot_list_2_cmd_2_ext4load[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ext4load);
extern char _u_boot_list_2_cmd_2_ext4ls[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ext4ls);
extern char _u_boot_list_2_cmd_2_ext4size[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ext4size);
extern char _u_boot_list_2_cmd_2_ext4write[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ext4write);
extern char _u_boot_list_2_cmd_2_false[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_false);
extern char _u_boot_list_2_cmd_2_fastboot[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fastboot);
extern char _u_boot_list_2_cmd_2_fatinfo[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fatinfo);
extern char _u_boot_list_2_cmd_2_fatload[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fatload);
extern char _u_boot_list_2_cmd_2_fatls[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fatls);
extern char _u_boot_list_2_cmd_2_fatmkdir[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fatmkdir);
extern char _u_boot_list_2_cmd_2_fatrm[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fatrm);
extern char _u_boot_list_2_cmd_2_fatsize[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fatsize);
extern char _u_boot_list_2_cmd_2_fatwrite[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fatwrite);
extern char _u_boot_list_2_cmd_2_fdt[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fdt);
extern char _u_boot_list_2_cmd_2_fstype[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fstype);
extern char _u_boot_list_2_cmd_2_fstypes[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fstypes);
extern char _u_boot_list_2_cmd_2_fsuuid[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fsuuid);
extern char _u_boot_list_2_cmd_2_fuse[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_fuse);
extern char _u_boot_list_2_cmd_2_go[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_go);
extern char _u_boot_list_2_cmd_2_gpio[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_gpio);
extern char _u_boot_list_2_cmd_2_gpt[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_gpt);
extern char _u_boot_list_2_cmd_2_gzwrite[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_gzwrite);
extern char _u_boot_list_2_cmd_2_hello_android[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_hello_android);
extern char _u_boot_list_2_cmd_2_help[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_help);
extern char _u_boot_list_2_cmd_2_i2c[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_i2c);
extern char _u_boot_list_2_cmd_2_icache[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_icache);
extern char _u_boot_list_2_cmd_2_iminfo[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_iminfo);
extern char _u_boot_list_2_cmd_2_imxtract[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_imxtract);
extern char _u_boot_list_2_cmd_2_itest[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_itest);
extern char _u_boot_list_2_cmd_2_ln[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ln);
extern char _u_boot_list_2_cmd_2_load[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_load);
extern char _u_boot_list_2_cmd_2_loadb[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_loadb);
extern char _u_boot_list_2_cmd_2_loads[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_loads);
extern char _u_boot_list_2_cmd_2_loadx[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_loadx);
extern char _u_boot_list_2_cmd_2_loady[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_loady);
extern char _u_boot_list_2_cmd_2_lock_status[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_lock_status);
extern char _u_boot_list_2_cmd_2_loop[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_loop);
extern char _u_boot_list_2_cmd_2_ls[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ls);
extern char _u_boot_list_2_cmd_2_lzmadec[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_lzmadec);
extern char _u_boot_list_2_cmd_2_md[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_md);
extern char _u_boot_list_2_cmd_2_mdio[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_mdio);
extern char _u_boot_list_2_cmd_2_mii[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_mii);
extern char _u_boot_list_2_cmd_2_mm[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_mm);
extern char _u_boot_list_2_cmd_2_mmc[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_mmc);
extern char _u_boot_list_2_cmd_2_mmcinfo[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_mmcinfo);
extern char _u_boot_list_2_cmd_2_mw[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_mw);
extern char _u_boot_list_2_cmd_2_net[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_net);
extern char _u_boot_list_2_cmd_2_nm[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_nm);
extern char _u_boot_list_2_cmd_2_panic[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_panic);
extern char _u_boot_list_2_cmd_2_part[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_part);
extern char _u_boot_list_2_cmd_2_ping[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_ping);
extern char _u_boot_list_2_cmd_2_pinmux[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_pinmux);
extern char _u_boot_list_2_cmd_2_printenv[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_printenv);
extern char _u_boot_list_2_cmd_2_question_mark[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_question_mark);
extern char _u_boot_list_2_cmd_2_random[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_random);
extern char _u_boot_list_2_cmd_2_read[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_read);
extern char _u_boot_list_2_cmd_2_regulator[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_regulator);
extern char _u_boot_list_2_cmd_2_reset[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_reset);
extern char _u_boot_list_2_cmd_2_run[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_run);
extern char _u_boot_list_2_cmd_2_save[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_save);
extern char _u_boot_list_2_cmd_2_saveenv[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_saveenv);
extern char _u_boot_list_2_cmd_2_setenv[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_setenv);
extern char _u_boot_list_2_cmd_2_setexpr[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_setexpr);
extern char _u_boot_list_2_cmd_2_showvar[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_showvar);
extern char _u_boot_list_2_cmd_2_size[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_size);
extern char _u_boot_list_2_cmd_2_sleep[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_sleep);
extern char _u_boot_list_2_cmd_2_source[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_source);
extern char _u_boot_list_2_cmd_2_test[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_test);
extern char _u_boot_list_2_cmd_2_tftpboot[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_tftpboot);
extern char _u_boot_list_2_cmd_2_true[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_true);
extern char _u_boot_list_2_cmd_2_unbind[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_unbind);
extern char _u_boot_list_2_cmd_2_unlz4[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_unlz4);
extern char _u_boot_list_2_cmd_2_unzip[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_unzip);
extern char _u_boot_list_2_cmd_2_usb[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_usb);
extern char _u_boot_list_2_cmd_2_usbboot[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_usbboot);
extern char _u_boot_list_2_cmd_2_version[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_version);
extern char _u_boot_list_2_cmd_2_write[];
__ADDRESSABLE(_u_boot_list_2_cmd_2_write);
extern char _u_boot_list_2_driver_2_blk_partition[];
__ADDRESSABLE(_u_boot_list_2_driver_2_blk_partition);
extern char _u_boot_list_2_driver_2_bootmeth_1extlinux[];
__ADDRESSABLE(_u_boot_list_2_driver_2_bootmeth_1extlinux);
extern char _u_boot_list_2_driver_2_bootmeth_efi[];
__ADDRESSABLE(_u_boot_list_2_driver_2_bootmeth_efi);
extern char _u_boot_list_2_driver_2_bootstd_drv[];
__ADDRESSABLE(_u_boot_list_2_driver_2_bootstd_drv);
extern char _u_boot_list_2_driver_2_ccf_clk_divider[];
__ADDRESSABLE(_u_boot_list_2_driver_2_ccf_clk_divider);
extern char _u_boot_list_2_driver_2_ccf_clk_mux[];
__ADDRESSABLE(_u_boot_list_2_driver_2_ccf_clk_mux);
extern char _u_boot_list_2_driver_2_clk_composite[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_composite);
extern char _u_boot_list_2_driver_2_clk_fixed_factor[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_fixed_factor);
extern char _u_boot_list_2_driver_2_clk_fixed_rate_raw[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_fixed_rate_raw);
extern char _u_boot_list_2_driver_2_clk_gate[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_gate);
extern char _u_boot_list_2_driver_2_clk_gate2[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_gate2);
extern char _u_boot_list_2_driver_2_clk_pfd[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_pfd);
extern char _u_boot_list_2_driver_2_clk_pll1416x[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_pll1416x);
extern char _u_boot_list_2_driver_2_clk_pll1443x[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_pll1443x);
extern char _u_boot_list_2_driver_2_clk_pllv3_av[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_pllv3_av);
extern char _u_boot_list_2_driver_2_clk_pllv3_enet[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_pllv3_enet);
extern char _u_boot_list_2_driver_2_clk_pllv3_generic[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_pllv3_generic);
extern char _u_boot_list_2_driver_2_clk_pllv3_genericv2[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_pllv3_genericv2);
extern char _u_boot_list_2_driver_2_clk_pllv3_sys[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_pllv3_sys);
extern char _u_boot_list_2_driver_2_clk_pllv3_usb[];
__ADDRESSABLE(_u_boot_list_2_driver_2_clk_pllv3_usb);
extern char _u_boot_list_2_driver_2_dwc3_generic_host[];
__ADDRESSABLE(_u_boot_list_2_driver_2_dwc3_generic_host);
extern char _u_boot_list_2_driver_2_dwc3_generic_peripheral[];
__ADDRESSABLE(_u_boot_list_2_driver_2_dwc3_generic_peripheral);
extern char _u_boot_list_2_driver_2_dwc3_generic_wrapper[];
__ADDRESSABLE(_u_boot_list_2_driver_2_dwc3_generic_wrapper);
extern char _u_boot_list_2_driver_2_dwc3_of_simple[];
__ADDRESSABLE(_u_boot_list_2_driver_2_dwc3_of_simple);
extern char _u_boot_list_2_driver_2_efi_blk[];
__ADDRESSABLE(_u_boot_list_2_driver_2_efi_blk);
extern char _u_boot_list_2_driver_2_efi_block[];
__ADDRESSABLE(_u_boot_list_2_driver_2_efi_block);
extern char _u_boot_list_2_driver_2_eth_bootdev[];
__ADDRESSABLE(_u_boot_list_2_driver_2_eth_bootdev);
extern char _u_boot_list_2_driver_2_eth_phy_generic_drv[];
__ADDRESSABLE(_u_boot_list_2_driver_2_eth_phy_generic_drv);
extern char _u_boot_list_2_driver_2_fecmxc_gem[];
__ADDRESSABLE(_u_boot_list_2_driver_2_fecmxc_gem);
extern char _u_boot_list_2_driver_2_fixed_clock[];
__ADDRESSABLE(_u_boot_list_2_driver_2_fixed_clock);
extern char _u_boot_list_2_driver_2_fsl_esdhc[];
__ADDRESSABLE(_u_boot_list_2_driver_2_fsl_esdhc);
extern char _u_boot_list_2_driver_2_gpio_mxc[];
__ADDRESSABLE(_u_boot_list_2_driver_2_gpio_mxc);
extern char _u_boot_list_2_driver_2_gpio_regulator[];
__ADDRESSABLE(_u_boot_list_2_driver_2_gpio_regulator);
extern char _u_boot_list_2_driver_2_i2c_eeprom_partition[];
__ADDRESSABLE(_u_boot_list_2_driver_2_i2c_eeprom_partition);
extern char _u_boot_list_2_driver_2_i2c_eeprom_std[];
__ADDRESSABLE(_u_boot_list_2_driver_2_i2c_eeprom_std);
extern char _u_boot_list_2_driver_2_i2c_generic_chip_drv[];
__ADDRESSABLE(_u_boot_list_2_driver_2_i2c_generic_chip_drv);
extern char _u_boot_list_2_driver_2_i2c_mxc[];
__ADDRESSABLE(_u_boot_list_2_driver_2_i2c_mxc);
extern char _u_boot_list_2_driver_2_imx8mp_clk[];
__ADDRESSABLE(_u_boot_list_2_driver_2_imx8mp_clk);
extern char _u_boot_list_2_driver_2_imx8mq_pinctrl[];
__ADDRESSABLE(_u_boot_list_2_driver_2_imx8mq_pinctrl);
extern char _u_boot_list_2_driver_2_imx_clk_fixed_factor[];
__ADDRESSABLE(_u_boot_list_2_driver_2_imx_clk_fixed_factor);
extern char _u_boot_list_2_driver_2_imx_wdt[];
__ADDRESSABLE(_u_boot_list_2_driver_2_imx_wdt);
extern char _u_boot_list_2_driver_2_mmc_blk[];
__ADDRESSABLE(_u_boot_list_2_driver_2_mmc_blk);
extern char _u_boot_list_2_driver_2_mmc_bootdev[];
__ADDRESSABLE(_u_boot_list_2_driver_2_mmc_bootdev);
extern char _u_boot_list_2_driver_2_nxp_imx8mq_usb_phy[];
__ADDRESSABLE(_u_boot_list_2_driver_2_nxp_imx8mq_usb_phy);
extern char _u_boot_list_2_driver_2_pinconfig_generic[];
__ADDRESSABLE(_u_boot_list_2_driver_2_pinconfig_generic);
extern char _u_boot_list_2_driver_2_psci[];
__ADDRESSABLE(_u_boot_list_2_driver_2_psci);
extern char _u_boot_list_2_driver_2_psci_sysreset[];
__ADDRESSABLE(_u_boot_list_2_driver_2_psci_sysreset);
extern char _u_boot_list_2_driver_2_regulator_fixed[];
__ADDRESSABLE(_u_boot_list_2_driver_2_regulator_fixed);
extern char _u_boot_list_2_driver_2_regulator_fixed_clock[];
__ADDRESSABLE(_u_boot_list_2_driver_2_regulator_fixed_clock);
extern char _u_boot_list_2_driver_2_root_driver[];
__ADDRESSABLE(_u_boot_list_2_driver_2_root_driver);
extern char _u_boot_list_2_driver_2_serial_mxc[];
__ADDRESSABLE(_u_boot_list_2_driver_2_serial_mxc);
extern char _u_boot_list_2_driver_2_simple_bus[];
__ADDRESSABLE(_u_boot_list_2_driver_2_simple_bus);
extern char _u_boot_list_2_driver_2_usb_bootdev[];
__ADDRESSABLE(_u_boot_list_2_driver_2_usb_bootdev);
extern char _u_boot_list_2_driver_2_usb_dev_generic_drv[];
__ADDRESSABLE(_u_boot_list_2_driver_2_usb_dev_generic_drv);
extern char _u_boot_list_2_driver_2_usb_generic_hub[];
__ADDRESSABLE(_u_boot_list_2_driver_2_usb_generic_hub);
extern char _u_boot_list_2_driver_2_usb_mass_storage[];
__ADDRESSABLE(_u_boot_list_2_driver_2_usb_mass_storage);
extern char _u_boot_list_2_driver_2_usb_storage_blk[];
__ADDRESSABLE(_u_boot_list_2_driver_2_usb_storage_blk);
extern char _u_boot_list_2_driver_2_vbe_simple[];
__ADDRESSABLE(_u_boot_list_2_driver_2_vbe_simple);
extern char _u_boot_list_2_driver_2_wdt_reboot[];
__ADDRESSABLE(_u_boot_list_2_driver_2_wdt_reboot);
extern char _u_boot_list_2_driver_2_xhci_dwc3[];
__ADDRESSABLE(_u_boot_list_2_driver_2_xhci_dwc3);
extern char _u_boot_list_2_env_clbk_2_baudrate[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_baudrate);
extern char _u_boot_list_2_env_clbk_2_callbacks[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_callbacks);
extern char _u_boot_list_2_env_clbk_2_console[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_console);
extern char _u_boot_list_2_env_clbk_2_ethaddr[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_ethaddr);
extern char _u_boot_list_2_env_clbk_2_flags[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_flags);
extern char _u_boot_list_2_env_clbk_2_gatewayip[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_gatewayip);
extern char _u_boot_list_2_env_clbk_2_ipaddr[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_ipaddr);
extern char _u_boot_list_2_env_clbk_2_loadaddr[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_loadaddr);
extern char _u_boot_list_2_env_clbk_2_netmask[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_netmask);
extern char _u_boot_list_2_env_clbk_2_nvlan[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_nvlan);
extern char _u_boot_list_2_env_clbk_2_serialno[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_serialno);
extern char _u_boot_list_2_env_clbk_2_serverip[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_serverip);
extern char _u_boot_list_2_env_clbk_2_vlan[];
__ADDRESSABLE(_u_boot_list_2_env_clbk_2_vlan);
extern char _u_boot_list_2_env_driver_2_mmc[];
__ADDRESSABLE(_u_boot_list_2_env_driver_2_mmc);
extern char _u_boot_list_2_evspy_info_2_EVT_DM_POST_INIT_F_3_imx8m_check_clock[];
__ADDRESSABLE(_u_boot_list_2_evspy_info_2_EVT_DM_POST_INIT_F_3_imx8m_check_clock);
extern char _u_boot_list_2_evspy_info_2_EVT_FT_FIXUP_3_bootmeth_vbe_ft_fixup[];
__ADDRESSABLE(_u_boot_list_2_evspy_info_2_EVT_FT_FIXUP_3_bootmeth_vbe_ft_fixup);
extern char _u_boot_list_2_evspy_info_2_EVT_FT_FIXUP_3_bootmeth_vbe_simple_ft_fixup[];
__ADDRESSABLE(_u_boot_list_2_evspy_info_2_EVT_FT_FIXUP_3_bootmeth_vbe_simple_ft_fixup);
extern char _u_boot_list_2_g_dnl_bind_callbacks_2___usb_function_name_usb_dnl_fastboot[];
__ADDRESSABLE(_u_boot_list_2_g_dnl_bind_callbacks_2___usb_function_name_usb_dnl_fastboot);
extern char _u_boot_list_2_g_dnl_bind_callbacks_2___usb_function_name_usb_dnl_ums[];
__ADDRESSABLE(_u_boot_list_2_g_dnl_bind_callbacks_2___usb_function_name_usb_dnl_ums);
extern char _u_boot_list_2_part_driver_2_a_efi[];
__ADDRESSABLE(_u_boot_list_2_part_driver_2_a_efi);
extern char _u_boot_list_2_part_driver_2_dos[];
__ADDRESSABLE(_u_boot_list_2_part_driver_2_dos);
extern char _u_boot_list_2_phy_driver_2_dp83867[];
__ADDRESSABLE(_u_boot_list_2_phy_driver_2_dp83867);
extern char _u_boot_list_2_phy_driver_2_genphy[];
__ADDRESSABLE(_u_boot_list_2_phy_driver_2_genphy);
extern char _u_boot_list_2_uclass_driver_2_blk[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_blk);
extern char _u_boot_list_2_uclass_driver_2_bootdev[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_bootdev);
extern char _u_boot_list_2_uclass_driver_2_bootmeth[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_bootmeth);
extern char _u_boot_list_2_uclass_driver_2_bootstd[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_bootstd);
extern char _u_boot_list_2_uclass_driver_2_clk[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_clk);
extern char _u_boot_list_2_uclass_driver_2_efi[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_efi);
extern char _u_boot_list_2_uclass_driver_2_eth_phy_generic[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_eth_phy_generic);
extern char _u_boot_list_2_uclass_driver_2_ethernet[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_ethernet);
extern char _u_boot_list_2_uclass_driver_2_firmware[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_firmware);
extern char _u_boot_list_2_uclass_driver_2_gpio[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_gpio);
extern char _u_boot_list_2_uclass_driver_2_i2c[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_i2c);
extern char _u_boot_list_2_uclass_driver_2_i2c_eeprom[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_i2c_eeprom);
extern char _u_boot_list_2_uclass_driver_2_i2c_generic[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_i2c_generic);
extern char _u_boot_list_2_uclass_driver_2_misc[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_misc);
extern char _u_boot_list_2_uclass_driver_2_mmc[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_mmc);
extern char _u_boot_list_2_uclass_driver_2_nop[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_nop);
extern char _u_boot_list_2_uclass_driver_2_partition[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_partition);
extern char _u_boot_list_2_uclass_driver_2_phy[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_phy);
extern char _u_boot_list_2_uclass_driver_2_pinconfig[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_pinconfig);
extern char _u_boot_list_2_uclass_driver_2_pinctrl[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_pinctrl);
extern char _u_boot_list_2_uclass_driver_2_regulator[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_regulator);
extern char _u_boot_list_2_uclass_driver_2_root[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_root);
extern char _u_boot_list_2_uclass_driver_2_serial[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_serial);
extern char _u_boot_list_2_uclass_driver_2_simple_bus[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_simple_bus);
extern char _u_boot_list_2_uclass_driver_2_sysreset[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_sysreset);
extern char _u_boot_list_2_uclass_driver_2_thermal[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_thermal);
extern char _u_boot_list_2_uclass_driver_2_usb[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_usb);
extern char _u_boot_list_2_uclass_driver_2_usb_dev_generic[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_usb_dev_generic);
extern char _u_boot_list_2_uclass_driver_2_usb_gadget_generic[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_usb_gadget_generic);
extern char _u_boot_list_2_uclass_driver_2_usb_hub[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_usb_hub);
extern char _u_boot_list_2_uclass_driver_2_usb_mass_storage[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_usb_mass_storage);
extern char _u_boot_list_2_uclass_driver_2_wdt[];
__ADDRESSABLE(_u_boot_list_2_uclass_driver_2_wdt);
extern char _u_boot_list_2_usb_driver_entry_2_usb_generic_hub[];
__ADDRESSABLE(_u_boot_list_2_usb_driver_entry_2_usb_generic_hub);
extern char _u_boot_list_2_usb_driver_entry_2_usb_mass_storage[];
__ADDRESSABLE(_u_boot_list_2_usb_driver_entry_2_usb_mass_storage);
