h = gopal.h
cc = gcc
cflag = -c
obj = main_file.o sum_digits.o
a.out: $(obj)
	$(cc) $(obj)
main_file.o: main_file.c
	$(cc) $(cflag) main_file.c $(h)
sum_digits.o: sum_digits.c
	$(cc) $(cflag) sum_digits.c $(h)
	
	 
